[package]
name = "nostr-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
nostr-sdk = "0.37"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
hex = "0.4"
